/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.java_deneme;

import java.awt.List;
import java.util.*;

/**
 *
 * @author Metin
 */
public class panelFormu extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(panelFormu.class.getName());

    /**
     * Creates new form panelFormu
     */
    public panelFormu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButtonGiris = new javax.swing.JButton();
        jTextFieldNumara = new javax.swing.JTextField();
        jTextFieldAd = new javax.swing.JTextField();
        jTextFieldSoyad = new javax.swing.JTextField();
        jTextFieldBolum = new javax.swing.JTextField();
        jTextFieldGno = new javax.swing.JTextField();
        jTextFieldYas = new javax.swing.JTextField();
        jTextFieldSonuc = new javax.swing.JTextField();
        jButtonDers = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Öğrenci Numarası");

        jLabel2.setText("Soyadı");

        jLabel3.setText("Adı");

        jLabel4.setText("Bölüm");

        jLabel5.setText("Gno");

        jLabel7.setText("Yas");

        jButtonGiris.setText("Giriş");
        jButtonGiris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGirisActionPerformed(evt);
            }
        });

        jTextFieldSonuc.setText("Sonuc");
        jTextFieldSonuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSonucActionPerformed(evt);
            }
        });

        jButtonDers.setText("Ders Çalış");
        jButtonDers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDersActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(138, 138, 138)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldNumara)
                            .addComponent(jTextFieldAd)
                            .addComponent(jTextFieldSoyad)
                            .addComponent(jTextFieldBolum)
                            .addComponent(jTextFieldGno)
                            .addComponent(jTextFieldYas)
                            .addComponent(jButtonGiris, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)))
                    .addComponent(jTextFieldSonuc, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addComponent(jButtonDers, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNumara, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldAd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldSoyad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldBolum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldGno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldYas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addComponent(jButtonGiris)
                .addGap(67, 67, 67)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldSonuc, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDers, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(78, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGirisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGirisActionPerformed
        Ogrenci o1 = new Ogrenci(Integer.parseInt(jTextFieldNumara.getText()));
        //o1.setNumara(Integer.parseInt(jTextFieldNumara.getText()));   //constructor sayesinde yazmamıza gerek kalmadı
        o1.setAdi(jTextFieldAd.getText());    //veri almak
        o1.setSoyadi(jTextFieldAd.getText());
        o1.setGno(Double.parseDouble(jTextFieldGno.getText()));                    //Double.parseDouble(jTextFieldGno.getText());
        o1.setYas(Integer.parseInt(jTextFieldYas.getText()));                        //Integer.parseInt(jTextFieldYas.getText());
        o1.setBolum(jTextFieldBolum.getText());
        Ders d1 =new Ders();    //önce nesne oluşturduk
        
        //o1.setOgrders(d1);      //içerisine atadık.
        //o1.getOgrders().setDersadi("Matematik");
        /*
        o1.getOgrders().setDerskodu(1);
        o1.getOgrders().setDonemi("güz");
        o1.getOgrders().setKredi(5);
        o1.getOgrders().setSinifi(2);
        */
        
        d1.setDersadi("Matematik");
        d1.setDerskodu(1);
        d1.setDonemi("güz");
        d1.setKredi(5);
        d1.setSinifi(2);
        o1.getOgrders().add(d1);
        o1.getOgrders().add(d1);
        
        o1.dersCalis();
        o1.cokCalis(0.5);
        o1.yazdir();
        jTextFieldGno.setText(String.valueOf(o1.getGno()));     //String'e çevirme
        jTextFieldSonuc.setText("GNO: "+o1.getGno());
        /*
        if(o1.yas >=20)
        jTextFieldSonuc.setText("adı "+o1.getAdi());    //veri göndermek
        else
        jTextFieldSonuc.setText("soyadi "+o1.getSoyadi());
        */
        /*
        int[] liste = new int[5];
        liste[0] = 1;
        liste[1] = 500;
        for(int i = 0; i<liste.length;i++)
        {
            System.err.println(liste[i]);
        }
        */
        //Ogrenci[] liste = new Ogrenci[5];
        ArrayList<Ogrenci> liste = new ArrayList<Ogrenci>();
        liste.add(o1);
        liste.add(o1);
        /*
        liste[0] = o1;
        liste[1] = o1;
        liste[2] = o1;
        liste[3] = o1;
        liste[4] = o1;
        */
        //for(int i = 0; i<liste.length;i++)
        /*
        for(int i = 0; i<liste.size();i++)
        {
            //System.err.println(liste[i]);   //bu şekilde olduğunda nesnenin referans yazar.
            //System.err.println(liste[i].getAdi());
            System.err.println(liste.get(i).getOgrders().getDersadi());
            
        }
        */
        
        for(int i = 0; i<liste.size();i++)
        {
            //System.err.println(liste[i]);   //bu şekilde olduğunda nesnenin referans yazar.
            //System.err.println(liste[i].getAdi());
            for(int j = 0; j < liste.get(i).getOgrders().size();j++)
            System.err.println(liste.get(i).getOgrders().get(j).getDersadi());
            
            
        }
        
        
    }//GEN-LAST:event_jButtonGirisActionPerformed

    private void jTextFieldSonucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSonucActionPerformed

    }//GEN-LAST:event_jTextFieldSonucActionPerformed

    private void jButtonDersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDersActionPerformed

    }//GEN-LAST:event_jButtonDersActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new panelFormu().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDers;
    private javax.swing.JButton jButtonGiris;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldAd;
    private javax.swing.JTextField jTextFieldBolum;
    private javax.swing.JTextField jTextFieldGno;
    private javax.swing.JTextField jTextFieldNumara;
    private javax.swing.JTextField jTextFieldSonuc;
    private javax.swing.JTextField jTextFieldSoyad;
    private javax.swing.JTextField jTextFieldYas;
    // End of variables declaration//GEN-END:variables
}
